Fix Quaternion SLerp Implementation
utilForever/CubbyFlow pull request #115
Opened 2021-07-24 12:07 UTC by Snowapril

### Known Issues
* Compile error in Slerp implementation `[ msvc 19.29.30040 x64 ]`

### Changes

#### 1. Modify Dot method misuse
##### Before
```c++
T cosHalfAngle = dot(a, b);
```
##### After
```c++
T cosHalfAngle = a.Dot(b);
```

#### 2. Add const keyword to Quaternion::Dot method
```c++
[[nodiscard]] T Dot(const Quaternion<T>& other) const;
```

#### 3. Add Unit-test code for quaternion slerp
```c++
TEST(Quaternion, Slerp)
{
    QuaternionD q1( 1.0f, 0.0f, 1.0f, 0.0f);
    QuaternionD q2(-1.0f, 0.0f, 1.0f, 0.0f);

    {
        QuaternionD q = Slerp(q1, q2, 0.0);

        EXPECT_DOUBLE_EQ(q1.x, q.x);
        EXPECT_DOUBLE_EQ(q1.y, q.y);
        EXPECT_DOUBLE_EQ(q1.z, q.z);
        EXPECT_DOUBLE_EQ(q1.w, q.w);
    }
    {
        QuaternionD q = Slerp(q1, q2, 1.0);

        EXPECT_DOUBLE_EQ(q2.x, q.x);
        EXPECT_DOUBLE_EQ(q2.y, q.y);
        EXPECT_DOUBLE_EQ(q2.z, q.z);
        EXPECT_DOUBLE_EQ(q2.w, q.w);
    }
    {
        QuaternionD q = Slerp(q1, q2, 0.5);

        EXPECT_DOUBLE_EQ(0.0, q.x);
        EXPECT_DOUBLE_EQ(1.414213562373095, q.y);
        EXPECT_DOUBLE_EQ(0.0, q.z);
        EXPECT_DOUBLE_EQ(0.0, q.w);
    }
}
```

### References
* https://www.euclideanspace.com/maths/algebra/realNormedAlgebra/quaternions/slerp/index.htm

2021-07-24 12:12 UTC, DveloperY0115 commented
Thanks for your work :)

2021-07-24 12:47 UTC, utilForever requested changes
Please check build status. 😢

2021-07-24 12:52 UTC, DveloperY0115 commented
> Please check build status. 😢

**C1002: compiler is out of heap space in pass 2**

Hmm.. Looks like something's going wrong when compiling the codes.

2021-07-24 13:50 UTC, Snowapril commented
Maybe there was something wrong with the CI server. Re-run workflow and works fine :)

2021-07-25 13:31 UTC, utilForever approved these changes
LGTM. Thanks for the fix! 🛠️

2021-07-25 13:31 UTC, merged